// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvilNxcubXUluL3ptRRVYk4eAdei0aIas',
    appId: '1:398226895490:web:8f2b92600c7578cef77a9b',
    messagingSenderId: '398226895490',
    projectId: 'todoapp-35875',
    authDomain: 'todoapp-35875.firebaseapp.com',
    storageBucket: 'todoapp-35875.appspot.com',
    measurementId: 'G-864075DDRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqcuuRZZ0bIo5m1ResQH4xB-0zPmS3GZ4',
    appId: '1:398226895490:android:cab49394ac9474a3f77a9b',
    messagingSenderId: '398226895490',
    projectId: 'todoapp-35875',
    storageBucket: 'todoapp-35875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6MIS-YCVTISpDUrUYbKPfgIGO0m5tPys',
    appId: '1:398226895490:ios:f7197c89f96d9e70f77a9b',
    messagingSenderId: '398226895490',
    projectId: 'todoapp-35875',
    storageBucket: 'todoapp-35875.appspot.com',
    iosClientId: '398226895490-bp02a1clbftgp9u9fp53eof9n7do3ate.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6MIS-YCVTISpDUrUYbKPfgIGO0m5tPys',
    appId: '1:398226895490:ios:f7197c89f96d9e70f77a9b',
    messagingSenderId: '398226895490',
    projectId: 'todoapp-35875',
    storageBucket: 'todoapp-35875.appspot.com',
    iosClientId: '398226895490-bp02a1clbftgp9u9fp53eof9n7do3ate.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
